project:
  type: website
  output-dir: docs

website:
  title: "IS428"
  navbar:
    left:
      - href: introduction.qmd
        text: Introduction
      - href: index.ipynb
        text: Home

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto